export const LOAD_PRODUCT_START="LOAD_PRODUCT_START";
export const LOAD_PRODUCT_SUCCESS="LOAD_PRODUCT_SUCCESS";
export const LOAD_PRODUCT_ERROR="LOAD_PRODUCT_ERROR";

export const ADD_T0_CART="ADD_TO_CART";
export const ADD_TO_CART_START="ADD_TO_CART_START";
export const DELETE_TO_CART="DELETE_TO_CART";
export const DELETE_TO_CART_START="DELETE_TO_CART_START";

export const DECREMENT_CART_QUANTITY="DECREMENT_CART_QUALITY";
export const DECREMENT_CART_QUANTITY_START="DECREMENT_CART_QUALITY_START";


export const CLEAR_TO_CART="CLEAR_TO_CART";
export const CLEAR_TO_CART_START="CLEAR_TO_CART_START";

export const GET_TOTAL_CART="GET_TOTAL_CART";
export const GET_TOTAL_CART_START="GET_TOTAL_CART_START"
export const OCCURED_ERROR = "OCCURED_ERROR";
